version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_voluntariado
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bd_voluntariado
      MYSQL_USER: voluntario_user
      MYSQL_PASSWORD: voluntario_pass
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      # Opcional: script de inicialización
      # - ./Bd/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - red-voluntariado

networks:
  red-voluntariado:
    driver: bridge
